title: Francesc Hinojosa # your name (or website title) here
logo: "/images/Francesc Hinojosa Data Scientist.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>As a forward-thinking professional, I have consistently demonstrated my prowess as an innovation leader in product development and service throughout my career.<br>
  <br><br>
  <a href="https://www.linkedin.com/in/franhinomut/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
